// Apple Devices Types

export interface IPhone_Types{
phone_name: string,
phone_ram: string,
phone_rom: string,
phone_screen_type: string,
phone_curved_screen: string,
phone_screen_size: string,
phone_screen_resolution: string,
phone_chip: string,
phone_rear_camera_captors_number: string,
phone_rear_camera_captors: string,
phone_front_camera_captors_number: string,
phone_front_camera_captors: string,
phone_recording_video_def: string,
phone_dual_sim: string,
phone_esim: string,
phone_battery: string,
phone_ai_integrated: string,
phone_wired_charging: string,
phone_wireless_charging: string,
phone_mark: string,
phone_type: string,
phone_model: string,
phone_price: string,
phone_discount: string,
phone_price_discount: string,
phone_available_colors: string,
phone_release_date: string
}

export interface Ipad_Types {
  tablet_name: string,
  tablet_ram: string,
  tablet_rom: string,
  tablet_screen_type: string,
  tablet_curved_screen: string,
  tablet_screen_size: string,
  tablet_screen_resolution: string,
  tablet_chip: string,
  tablet_rear_camera_captors_number: string,
  tablet_rear_camera_captors: string,
  tablet_front_camera_captors_number: string,
  tablet_front_camera_captors: string,
  tablet_recording_video_def: string,
  tablet_physical_sim: string,
  tablet_esim: string,
  tablet_ai_integrated: string,
  tablet_touch_id: string,
  tablet_face_id: string,
  tablet_apple_pay: string,
  tablet_apple_pencil: string,
  tablet_magic_keyboard: string,
  tablet_battery: string,
  tablet_wired_charging: string,
  tablet_wireless_charging: string,
  tablet_mark: string,
  tablet_type: string,
  tablet_model: string,
  tablet_price: string,
  tablet_discount: string,
  tablet_price_discount: string,
  tablet_available_colors: string,
  tablet_release_date: string
}

export interface Macbook_Types{
computer_name: string,
product_picture: string,
computer_ram: string,
computer_rom: string,
computer_screen_type: string,
computer_screen_size: string,
computer_screen_resolution: string,
computer_touch_screen: string,
computer_chip: string,
computer_core_number: string,
computer_integrated_graphics: string,
computer_gpu_core_number: string,
computer_neural_engine_core: string,
computer_card_slot: string,
computer_hdmi_port: string,
computer_jack_port: string,
computer_magsafe_port: string,
computer_usbc_port: string,
computer_usbc_port_number: string,
computer_battery: string,
computer_battery_autonomy: string,
computer_os: string,
computer_camera: string,
computer_ai_integrated: string,
computer_touch_id: string,
computer_mark: string,
computer_type: string,
computer_model: string,
computer_price: string,
computer_discount: string,
computer_price_discount: string,
computer_release_date: string,
}

export interface Apple_Accessories_Types {
  apple_accessories_name: string,
  product_picture: string,
  apple_accessories_description: string,
  apple_accessories_mark: string,
  apple_accessories_type: string,
  apple_accessories_price: string,
  apple_accessories_discount: string,
  apple_accessories_price_discount: string,
  apple_accessories_release_date: string
}

export interface Airpods_Types {
  airpods_name: string,
  product_picture: string,
  airpods_mark: string,
  airpods_type: string,
  airpods_model: string,
  airpods_voice_isolation: string,
  airpods_active_noise_cancellation: string,
  airpods_listening_time: string,
  airpods_conversation_time: string,
  airpods_listening_time_anc: string,
  airpods_conversation_time_anc: string,
  airpods_bluetooth_version: string,
  airpods_price: string,
  airpods_discount: string,
  airpods_price_discount: string,
  airpods_release_date: string
}

// Samsung Devices Types

export interface Galaxy_Book_Types {
  computer_name: string,
  product_picture: string,
  computer_ram: string,
  computer_rom: string,
  computer_screen_type: string,
  computer_screen_size: string,
  computer_screen_resolution: string,
  computer_touch_screen: string,
  computer_anti_reflexive_glass: string,
  computer_chip: string,
  computer_chip_frequency: string,
  computer_core_number: string,
  computer_integrated_graphics: string,
  computer_npu: string,
  computer_card_slot: string,
  computer_hdmi_port: string,
  computer_jack_port: string,
  computer_usba_port: string,
  computer_usba_port_number: string,
  computer_usbc_port: string,
  computer_usbc_port_number: string,
  computer_battery: string,
  computer_battery_autonomy: string,
  computer_os: string,
  computer_camera: string,
  computer_ai_integrated: string,
  computer_copilot_key: string,
  computer_mark: string,
  computer_type: string,
  computer_model: string,
  computer_price: string,
  computer_discount: string,
  computer_price_discount: string,
  computer_release_date: string
}

export interface Galaxy_Phones {
phone_name: string,
product_picture: string,
phone_ram: string,
phone_rom: string,
phone_screen_type: string,
phone_curved_screen: string,
phone_screen_size: string,
phone_screen_resolution: string,
phone_chip: string,
phone_rear_camera_captors_number: string,
phone_rear_camera_captors: string,
phone_front_camera_captors_number: string,
phone_front_camera_captors: string,
phone_recording_video_def: string,
phone_dual_sim: string,
phone_esim: string,
phone_card_slot: string,
phone_dex: string,
phone_fingerprint: string,
phone_stylus: string,
phone_battery: string,
phone_galaxy_ai: string,
phone_wired_charging: string,
phone_wireless_charging: string,
phone_mark: string,
phone_type: string,
phone_model: string,
phone_price: string,
phone_discount: string,
phone_price_discount: string,
phone_available_colors: string,
phone_release_date: string
}

export interface Galaxy_Tablets {
  tablet_name: string,
  product_picture: string,
  tablet_ram: string,
  tablet_rom: string,
  tablet_screen_type: string,
  tablet_curved_screen: string,
  tablet_screen_size: string,
  tablet_screen_resolution: string,
  tablet_chip: string,
  tablet_rear_camera_captors_number: string,
  tablet_rear_camera_captors: string,
  tablet_front_camera_captors_number: string,
  tablet_front_camera_captors: string,
  tablet_recording_video_def: string,
  tablet_physical_sim: string,
  tablet_esim: string,
  tablet_card_slot: string,
  tablet_dex: string,
  tablet_fingerprint: string,
  tablet_stylus: string,
  tablet_battery: string,
  tablet_galaxy_ai: string,
  tablet_wired_charging: string,
  tablet_wireless_charging: string,
  tablet_mark: string,
  tablet_type: string,
  tablet_model: string,
  tablet_price: string,
  tablet_discount: string,
  tablet_price_discount: string,
  tablet_available_colors: string,
  tablet_release_date: string
}

export interface Galaxy_Buds {
  galaxybuds_name: string,
  product_picture: string,
  galaxybuds_mark: string,
  galaxybuds_type: string,
  galaxybuds_model: string,
  galaxybuds_voice_isolation: string,
  galaxybuds_active_noise_cancellation: string,
  galaxybuds_listening_time: string,
  galaxybuds_conversation_time: string,
  galaxybuds_listening_time_anc: string,
  galaxybuds_conversation_time_anc: string,
  galaxybuds_bluetooth_version: string,
  galaxybuds_price: string,
  galaxybuds_discount: string,
  galaxybuds_price_discount: string,
  galaxybuds_release_date: string
}

export interface Samsung_Accessories_Types {
  samsung_accessories_name: string,
  product_picture: string,
  samsung_accessories_description: string,
  samsung_accessories_mark: string,
  samsung_accessories_type: string,
  samsung_accessories_price: string,
  samsung_accessories_discount: string,
  samsung_accessories_price_discount: string,
  samsung_accessories_release_date: string
}